version: "3.3"
services:
  api-server:
    build: ./api-server
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres@postgres/crypto_data
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: crypto_data