version: "3.3"
services:
  api-server:
    build: ./api-server
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "dbname='crypto_data' user='db-user' host='postgres' password='db-user-pw'"
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-user-pw
      POSTGRES_DB: crypto_data
